language: ruby

rvm:
  - '1.8.7'
  - '2.1.8'
  - '2.2.4'
  - '2.3.1'
  - '2.4.1'

gemfile:
  - 'gemfiles/Gemfile.2.3.mysql2'
  - 'gemfiles/Gemfile.3.2.mysql2'
  - 'gemfiles/Gemfile.4.2.mysql2'
  - 'gemfiles/Gemfile.4.2.pg'
  - 'gemfiles/Gemfile.5.1.mysql2'
  - 'gemfiles/Gemfile.5.1.pg'

matrix:
  exclude:
    - gemfile: 'gemfiles/Gemfile.2.3.mysql2'
      rvm: '2.1.8'
    - gemfile: 'gemfiles/Gemfile.2.3.mysql2'
      rvm: '2.2.4'
    - gemfile: 'gemfiles/Gemfile.3.2.mysql2'
      rvm: '2.3.1'
    - gemfile: 'gemfiles/Gemfile.2.3.mysql2'
      rvm: '2.3.1'
    - gemfile: 'gemfiles/Gemfile.2.3.mysql2'
      rvm: '2.4.1'
    - gemfile: 'gemfiles/Gemfile.3.2.mysql2'
      rvm: '2.4.1'
    - gemfile: 'gemfiles/Gemfile.4.2.mysql2'
      rvm: '1.8.7'
    - gemfile: 'gemfiles/Gemfile.4.2.pg'
      rvm: '1.8.7'
    - gemfile: 'gemfiles/Gemfile.4.2.mysql2'
      rvm: '2.4.1'
    - gemfile: 'gemfiles/Gemfile.4.2.pg'
      rvm: '2.4.1'
    - gemfile: 'gemfiles/Gemfile.5.1.mysql2'
      rvm: '1.8.7'
    - gemfile: 'gemfiles/Gemfile.5.1.mysql2'
      rvm: '2.1.8'
    - gemfile: 'gemfiles/Gemfile.5.1.pg'
      rvm: '1.8.7'
    - gemfile: 'gemfiles/Gemfile.5.1.pg'
      rvm: '2.1.8'

services:
  - mysql

install:
  # Shave yaks
  - gem uninstall bundler -I -x --force
  # Old Travis CI bundler explodes when lockfile version doesn't match recently bumped version
  - gem install bundler --version='=1.12.5'
  # This is the default Travis CI install step
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}

before_script:
  - psql -c 'create database edge_rider_test;' -U postgres
  - mysql -e 'create database IF NOT EXISTS edge_rider_test;'

script: bundle exec rake current_rspec

notifications:
  email:
    - fail@makandra.de
