language: ruby

dist: trusty

matrix:
  include:
    - rvm: 2.2.4
      gemfile: Gemfile.3.2.mysql2
    - rvm: 2.2.4
      gemfile: Gemfile.4.2.mysql2
    - rvm: 2.3.1
      gemfile: Gemfile.4.2.mysql2
    - rvm: 2.2.4
      gemfile: Gemfile.4.2.pg
    - rvm: 2.3.1
      gemfile: Gemfile.4.2.pg
    - rvm: 2.2.4
      gemfile: Gemfile.5.2.mysql2
    - rvm: 2.3.1
      gemfile: Gemfile.5.2.mysql2
    - rvm: 2.4.1
      gemfile: Gemfile.5.2.mysql2
    - rvm: 2.5.3
      gemfile: Gemfile.5.2.mysql2
    - rvm: 2.2.4
      gemfile: Gemfile.5.2.pg
    - rvm: 2.3.1
      gemfile: Gemfile.5.2.pg
    - rvm: 2.4.1
      gemfile: Gemfile.5.2.pg
    - rvm: 2.5.3
      gemfile: Gemfile.5.2.pg
    - rvm: 2.5.3
      gemfile: Gemfile.6.0.pg

services:
  - mysql

install:
  # Replace default Travis CI bundler script with a version that doesn't
  # explode when lockfile doesn't match recently bumped version
  - bundle install --no-deployment --jobs=3 --retry=3 --path=${BUNDLE_PATH:-vendor/bundle}

addons:
  postgresql: 9.3

before_script:
  - psql -c 'create database edge_rider_test;' -U postgres
  - mysql -e 'create database IF NOT EXISTS edge_rider_test;'

script: bundle exec rake current_rspec
